forge 'http://forge.puppetlabs.com'

mod 'puppetlabs/postgresql'
mod 'stankevich/python',
 :git => 'git://github.com/stankevich/puppet-python.git'
# mod 'nesi/puppet-git',
#  :git => 'git://github.com/nesi/puppet-git.git'  
mod 'puppetlabs/puppetlabs-vcsrepo',
 :git => 'git://github.com/puppetlabs/puppetlabs-vcsrepo.git'